var cameraPosition = [-5.72, -15.27, 3.00];
module.exports = {
    bgColor: 0xD0D8D9,
    lightColor: 0xE0E0E0,
    fogDensity: 0.075,
    lightIntensity: 1.1,
    orbitCameraPosition: cameraPosition,
    spectatorCameraPosition: cameraPosition,
    landscapeMaxHeight: 1.8,
    landscapePlaneSize: 32,
    landscapePlaneDetails: 64,
    landscapeTextureResolution: 20.0,
    landscapeHeightmapTexture: 'resources/heightmap.png',
    landscapeGroundTexture: 'resources/snow-512.jpg',
    snowNumParticles: 25000,
    snowColor: 0xFFFFFF,
    snowRadiusX: 0.1,
    snowRadiusY: 0.1,
    snowSize: 10.0,
    snowScale: 1.0,
    snowOpacity: 0.5,
    firBranchTexture: 'resources/fir-branch-quad.png',
    firBranchesNum: 7,
    firBranchesSlope: 0.35,
    forestMap: 'resources/forestmap.png',
    forestTreesCount: 250,
    railroadTieModel: 'resources/railroad-tie.dae',
    bushTexture: 'resources/bush2.png'
}
