var cameraPosition = [-4.70, -14.30, 2.70];
module.exports = {
    bgColor: 0xD0D8D9,
    lightColor: 0xE0E0E0,
    fogDensity: 0.1,
    lightIntensity: 1.1,
    orbitCameraPosition: cameraPosition,
    spectatorCameraPosition: cameraPosition,
    landscapeMaxHeight: 1.8,
    landscapePlaneSize: 32,
    landscapePlaneDetails: 256,
    landscapeTextureResolution: 60.0,
    landscapeHeightmapTexture: 'resources/heightmap.png',
    landscapeSnowTexture: 'resources/snow-512.jpg',
    landscapeRocksTexture: 'resources/rocks-512.jpg',
    snowNumParticles: 25000,
    snowColor: 0xFFFFFF,
    snowRadiusX: 0.1,
    snowRadiusY: 0.1,
    snowSize: 10.0,
    snowScale: 1.0,
    snowOpacity: 0.5,
    firHeight: 2,
    firBranchTexture: 'resources/fir-branch-quad.png',
    firBranchesNum: 7,
    firBranchesSlope: 0.35,
    forestMap: 'resources/forestmap.png',
    forestPlaneTexture: 'resources/tree-pattern.png',
    railroadTieModel: 'resources/railroad-tie.dae',
    bushTexture: 'resources/bush2.png',
    flagBackground: 'resources/flag.png',
    railTexture: 'resources/railTexture.png',
    tieTexture: 'resources/tieTexture.png',
    getTimeUrl: 'http://doobki.ru/gettime.php'
}
